//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from rasm.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class rasmLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		KEYWORD=1, SPECIAL_KEYWORD=2, LABEL=3, ARG=4, WORD=5, OCTAL=6, DECIMAL=7, 
		HEXADECIMAL=8, COMMENT=9, NL=10, WS=11;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"KEYWORD", "SPECIAL_KEYWORD", "LABEL", "ARG", "WORD", "OCTAL", "DECIMAL", 
		"HEXADECIMAL", "COMMENT", "NL", "WS"
	};


	public rasmLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public rasmLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "KEYWORD", "SPECIAL_KEYWORD", "LABEL", "ARG", "WORD", "OCTAL", "DECIMAL", 
		"HEXADECIMAL", "COMMENT", "NL", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "rasm.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static rasmLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\r', '\x89', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x5', '\x2', '\x41', '\n', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x5', '\x3', 'N', '\n', '\x3', '\x3', '\x4', '\x6', '\x4', 'Q', '\n', 
		'\x4', '\r', '\x4', '\xE', '\x4', 'R', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '[', '\n', 
		'\x5', '\x3', '\x6', '\x6', '\x6', '^', '\n', '\x6', '\r', '\x6', '\xE', 
		'\x6', '_', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', '\x65', 
		'\n', '\a', '\f', '\a', '\xE', '\a', 'h', '\v', '\a', '\x3', '\b', '\x5', 
		'\b', 'k', '\n', '\b', '\x3', '\b', '\x6', '\b', 'n', '\n', '\b', '\r', 
		'\b', '\xE', '\b', 'o', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x6', '\t', 'v', '\n', '\t', '\r', '\t', '\xE', '\t', 'w', '\x3', 
		'\n', '\x3', '\n', '\a', '\n', '|', '\n', '\n', '\f', '\n', '\xE', '\n', 
		'\x7F', '\v', '\n', '\x3', '\v', '\x5', '\v', '\x82', '\n', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x2', '\x2', '\r', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', 
		'\f', '\x17', '\r', '\x3', '\x2', '\n', '\x5', '\x2', '\x32', ';', '\x43', 
		'\\', '\x63', '|', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', 
		'\x33', '\x39', '\x3', '\x2', '\x32', '\x39', '\x3', '\x2', '\x32', ';', 
		'\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', '\x4', '\x2', '\f', 
		'\f', '\xF', '\xF', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x2', '\x9F', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x3', '@', '\x3', '\x2', '\x2', '\x2', 
		'\x5', 'M', '\x3', '\x2', '\x2', '\x2', '\a', 'P', '\x3', '\x2', '\x2', 
		'\x2', '\t', 'Z', '\x3', '\x2', '\x2', '\x2', '\v', ']', '\x3', '\x2', 
		'\x2', '\x2', '\r', '\x61', '\x3', '\x2', '\x2', '\x2', '\xF', 'j', '\x3', 
		'\x2', '\x2', '\x2', '\x11', 'q', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'y', '\x3', '\x2', '\x2', '\x2', '\x15', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '\x85', '\x3', '\x2', '\x2', '\x2', '\x19', '\x1A', '\a', 
		'\x63', '\x2', '\x2', '\x1A', '\x1B', '\a', '\x66', '\x2', '\x2', '\x1B', 
		'\x41', '\a', '\x66', '\x2', '\x2', '\x1C', '\x1D', '\a', '\x63', '\x2', 
		'\x2', '\x1D', '\x1E', '\a', '\x66', '\x2', '\x2', '\x1E', '\x1F', '\a', 
		'\x66', '\x2', '\x2', '\x1F', '\x41', '\a', 'k', '\x2', '\x2', ' ', '!', 
		'\a', 'p', '\x2', '\x2', '!', '\"', '\a', '\x63', '\x2', '\x2', '\"', 
		'#', '\a', 'p', '\x2', '\x2', '#', '\x41', '\a', '\x66', '\x2', '\x2', 
		'$', '%', '\a', 'n', '\x2', '\x2', '%', '&', '\a', 'w', '\x2', '\x2', 
		'&', '\x41', '\a', 'k', '\x2', '\x2', '\'', '(', '\a', 'u', '\x2', '\x2', 
		'(', '\x41', '\a', 'y', '\x2', '\x2', ')', '*', '\a', 'n', '\x2', '\x2', 
		'*', '\x41', '\a', 'y', '\x2', '\x2', '+', ',', '\a', '\x64', '\x2', '\x2', 
		',', '-', '\a', 'g', '\x2', '\x2', '-', '\x41', '\a', 's', '\x2', '\x2', 
		'.', '/', '\a', 'l', '\x2', '\x2', '/', '\x30', '\a', '\x63', '\x2', '\x2', 
		'\x30', '\x31', '\a', 'n', '\x2', '\x2', '\x31', '\x41', '\a', 't', '\x2', 
		'\x2', '\x32', '\x33', '\a', 'p', '\x2', '\x2', '\x33', '\x34', '\a', 
		'q', '\x2', '\x2', '\x34', '\x41', '\a', 'r', '\x2', '\x2', '\x35', '\x36', 
		'\a', 'j', '\x2', '\x2', '\x36', '\x37', '\a', '\x63', '\x2', '\x2', '\x37', 
		'\x38', '\a', 'n', '\x2', '\x2', '\x38', '\x41', '\a', 'v', '\x2', '\x2', 
		'\x39', ':', '\a', 'n', '\x2', '\x2', ':', ';', '\a', 'n', '\x2', '\x2', 
		';', '\x41', '\a', 'k', '\x2', '\x2', '<', '=', '\a', 'o', '\x2', '\x2', 
		'=', '>', '\a', 'q', '\x2', '\x2', '>', '?', '\a', 'x', '\x2', '\x2', 
		'?', '\x41', '\a', 'k', '\x2', '\x2', '@', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '@', '\x1C', '\x3', '\x2', '\x2', '\x2', '@', ' ', '\x3', '\x2', 
		'\x2', '\x2', '@', '$', '\x3', '\x2', '\x2', '\x2', '@', '\'', '\x3', 
		'\x2', '\x2', '\x2', '@', ')', '\x3', '\x2', '\x2', '\x2', '@', '+', '\x3', 
		'\x2', '\x2', '\x2', '@', '.', '\x3', '\x2', '\x2', '\x2', '@', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '@', '\x35', '\x3', '\x2', '\x2', '\x2', '@', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '@', '<', '\x3', '\x2', '\x2', '\x2', 
		'\x41', '\x4', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\a', '\x30', 
		'\x2', '\x2', '\x43', '\x44', '\a', 'h', '\x2', '\x2', '\x44', '\x45', 
		'\a', 'k', '\x2', '\x2', '\x45', '\x46', '\a', 'n', '\x2', '\x2', '\x46', 
		'N', '\a', 'n', '\x2', '\x2', 'G', 'H', '\a', '\x30', '\x2', '\x2', 'H', 
		'I', '\a', 'u', '\x2', '\x2', 'I', 'J', '\a', 'r', '\x2', '\x2', 'J', 
		'K', '\a', '\x63', '\x2', '\x2', 'K', 'L', '\a', '\x65', '\x2', '\x2', 
		'L', 'N', '\a', 'g', '\x2', '\x2', 'M', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'M', 'G', '\x3', '\x2', '\x2', '\x2', 'N', '\x6', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'Q', '\t', '\x2', '\x2', '\x2', 'P', 'O', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'R', '\x3', '\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'U', '\a', '<', '\x2', '\x2', 'U', '\b', '\x3', '\x2', '\x2', 
		'\x2', 'V', '[', '\x5', '\r', '\a', '\x2', 'W', '[', '\x5', '\xF', '\b', 
		'\x2', 'X', '[', '\x5', '\x11', '\t', '\x2', 'Y', '[', '\x5', '\v', '\x6', 
		'\x2', 'Z', 'V', '\x3', '\x2', '\x2', '\x2', 'Z', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'Z', 'X', '\x3', '\x2', '\x2', '\x2', 'Z', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '[', '\n', '\x3', '\x2', '\x2', '\x2', '\\', '^', '\t', '\x3', 
		'\x2', '\x2', ']', '\\', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', 
		'\x2', '\x2', '\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', 
		'\x2', '\x2', '\x2', '`', '\f', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', 
		'\a', '\x32', '\x2', '\x2', '\x62', '\x66', '\t', '\x4', '\x2', '\x2', 
		'\x63', '\x65', '\t', '\x5', '\x2', '\x2', '\x64', '\x63', '\x3', '\x2', 
		'\x2', '\x2', '\x65', 'h', '\x3', '\x2', '\x2', '\x2', '\x66', '\x64', 
		'\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\x3', '\x2', '\x2', '\x2', 'g', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'h', '\x66', '\x3', '\x2', '\x2', '\x2', 
		'i', 'k', '\a', '/', '\x2', '\x2', 'j', 'i', '\x3', '\x2', '\x2', '\x2', 
		'j', 'k', '\x3', '\x2', '\x2', '\x2', 'k', 'm', '\x3', '\x2', '\x2', '\x2', 
		'l', 'n', '\t', '\x6', '\x2', '\x2', 'm', 'l', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 'm', '\x3', '\x2', '\x2', '\x2', 
		'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\a', '\x32', '\x2', '\x2', 'r', 's', '\a', 'z', '\x2', 
		'\x2', 's', 'u', '\x3', '\x2', '\x2', '\x2', 't', 'v', '\t', '\a', '\x2', 
		'\x2', 'u', 't', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'u', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', '\x2', '\x2', 
		'\x2', 'x', '\x12', '\x3', '\x2', '\x2', '\x2', 'y', '}', '\a', '%', '\x2', 
		'\x2', 'z', '|', '\n', '\b', '\x2', '\x2', '{', 'z', '\x3', '\x2', '\x2', 
		'\x2', '|', '\x7F', '\x3', '\x2', '\x2', '\x2', '}', '{', '\x3', '\x2', 
		'\x2', '\x2', '}', '~', '\x3', '\x2', '\x2', '\x2', '~', '\x14', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', '}', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'\x82', '\a', '\xF', '\x2', '\x2', '\x81', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x84', '\a', '\f', '\x2', '\x2', '\x84', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\t', '\t', '\x2', 
		'\x2', '\x86', '\x87', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\b', 
		'\f', '\x2', '\x2', '\x88', '\x18', '\x3', '\x2', '\x2', '\x2', '\xE', 
		'\x2', '@', 'M', 'R', 'Z', '_', '\x66', 'j', 'o', 'w', '}', '\x81', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
